name: Horusec-Tester

on: pull_request

jobs:
  sec-scan:
    name: Run security scan
    runs-on: self-hosted
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Open powershell
        env:
          DATA: ${{ github.event.pull_request.labels.*.name }}
        run:  Foreach($label in process.env.DATA){ $label }
        shell: powershell
