name: Horusec-Tester

on: pull_request

jobs:
  sec-scan:
    name: Run security scan
    runs-on: self-hosted
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: CD to project directory
        shell: cmd
        run: |
          cd ${{ github.workspace }}
          FOR /F "tokens=* USEBACKQ" %temp IN (`dir testing.bat /b /s`) do (SET "$scriptPath=%temp")
          %$scriptPath%