name: Horusec-Tester

on: pull_request

jobs:
  sec-scan:
    name: Run security scan
    runs-on: self-hosted
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: CD to project directory
        shell: pwsh
        run: cd ${{ github.workspace }}
        
      - name: Find and Run Script
        shell: pwsh
        run: Invoke-Expression "cmd.exe -/c (Get-ChildItem testing.bat -Recurse).fullname"
